### ISSUE TITLE
thank you for creating the shadenodeloader - sadly it is outdated and does not work anymore, how to fix it?

### ISSUE THREAD

**Issue by mslitto** [donmccurdy/three-shadenodeloader#1]

**Comment by donmccurdy** [comment]
Hi! Yes, the three.js node material system has changed quite a bit since this was written. It should still be compatible with three.js r101. I haven't looked into what changes would be required to update it to recent three.js versions.

**Comment by mslitto** [comment]
Ok thx! We try to find a way.
